# Task 1

**This notebook does the following,**

1. Understand the input data and go through each column
2. Visualizes and Summarizes the data

## Import Packages

In [16]:
import pandas as pd
import matplotlib.pyplot as plt

## Load Data

In [17]:
twitterdf = pd.read_json('~/Local/datasets/corona-out-3',lines = True)

In [ ]:
twitterdf.describe()

,id,id_str,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,contributors,quote_count,reply_count,retweet_count,favorite_count,possibly_sensitive,quoted_status_id,quoted_status_id_str
count,1.019160e+05,1.019160e+05,1.361000e+04,1.361000e+04,1.485500e+04,1.485500e+04,0.0,101916.0,101916.0,101916.0,101916.0,27433.000000,1.612900e+04,1.612900e+04
mean,1.254042e+18,1.254042e+18,1.253564e+18,1.253564e+18,3.915265e+17,3.915265e+17,NaN,0.0,0.0,0.0,0.0,0.029964,1.252695e+18,1.252695e+18
std,1.064351e+13,1.064351e+13,8.544387e+15,8.544387e+15,5.177342e+17,5.177342e+17,NaN,0.0,0.0,0.0,0.0,0.170491,1.643782e+16,1.643782e+16
min,1.254023e+18,1.254023e+18,8.218186e+17,8.218186e+17,3.987000e+03,3.987000e+03,NaN,0.0,0.0,0.0,0.0,0.000000,3.395442e+17,3.395442e+17
25%,1.254033e+18,1.254033e+18,1.253953e+18,1.253953e+18,1.454341e+08,1.454341e+08,NaN,0.0,0.0,0.0,0.0,0.000000,1.253658e+18,1.253658e+18
50%,1.254042e+18,1.254042e+18,1.254026e+18,1.254026e+18,1.866939e+09,1.866939e+09,NaN,0.0,0.0,0.0,0.0,0.000000,1.253943e+18,1.253943e+18
75%,1.254051e+18,1.254051e+18,1.254041e+18,1.254041e+18,9.824704e+17,9.824704e+17,NaN,0.0,0.0,0.0,0.0,0.000000,1.254023e+18,1.254023e+18
max,1.254060e+18,1.254060e+18,1.254060e+18,1.254060e+18,1.254056e+18,1.254056e+18,NaN,0.0,0.0,0.0,0.0,1.000000,1.254059e+18,1.254059e+18

In [ ]:
twitterdf.isna().sum()

created_at                        0
id                                0
id_str                            0
text                              0
display_text_range            83792
source                            0
truncated                         0
in_reply_to_status_id         88306
in_reply_to_status_id_str     88306
in_reply_to_user_id           87061
in_reply_to_user_id_str       87061
in_reply_to_screen_name       87061
user                              0
geo                          101839
coordinates                  101839
place                        100545
contributors                 101916
is_quote_status                   0
quote_count                       0
reply_count                       0
retweet_count                     0
favorite_count                    0
entities                          0
extended_entities             94649
favorited                         0
retweeted                         0
possibly_sensitive            74483
filter_level                      0
lang                              0
timestamp_ms                      0
retweeted_status              40815
quoted_status_id              85787
quoted_status_id_str          85787
quoted_status                 85793
quoted_status_permalink       85793
extended_tweet                84156
withheld_in_countries        101870
dtype: int64

## Top tweet languages

In [ ]:
twitterdf.lang

,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,filter_level,lang,timestamp_ms,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,extended_tweet,withheld_in_countries
0,2020-04-25 12:21:41+00:00,1254022770679320576,1254022770679320576,"É isto, ou vou morrer sem ar ou com o corona h...","[0, 44]","<a href=""http://twitter.com/download/android"" ...",False,NaN,NaN,NaN,...,low,pt,2020-04-25 12:21:41.803,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-04-25 12:21:41+00:00,1254022770746372096,1254022770746372096,Schöne Runde mit dem Rennrad ✌️\n#sport #coron...,"[0, 46]","<a href=""http://twitter.com/download/iphone"" r...",False,NaN,NaN,NaN,...,low,de,2020-04-25 12:21:41.819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-04-25 12:21:42+00:00,1254022772558368768,1254022772558368768,RT @BJP4India: India’s war with Corona is ongo...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,NaN,NaN,...,low,en,2020-04-25 12:21:42.251,{'created_at': 'Sat Apr 25 07:30:12 +0000 2020...,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-04-25 12:21:42+00:00,1254022772575043586,1254022772575043584,Was sollen 150 Euro Computerzuschuss bringen? ...,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",True,NaN,NaN,NaN,...,low,de,2020-04-25 12:21:42.255,NaN,1.254016e+18,1.254016e+18,{'created_at': 'Sat Apr 25 11:56:31 +0000 2020...,"{'url': 'https://t.co/xn4jgGqfoY', 'expanded':...",{'full_text': 'Was sollen 150 Euro Computerzus...,NaN
4,2020-04-25 12:21:42+00:00,1254022772877131777,1254022772877131776,RT @schrodingerk42: @ozkan_yalim @DurmusYillma...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,NaN,NaN,...,low,tr,2020-04-25 12:21:42.327,{'created_at': 'Tue Apr 21 12:34:00 +0000 2020...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101911,2020-04-25 14:48:38+00:00,1254059751379361793,1254059751379361792,@VSReddy_MP I think wantedly you ate damaging ...,"[12, 140]","<a href=""http://twitter.com/download/android"" ...",True,1.253990e+18,1.253990e+18,8.151441e+17,...,low,en,2020-04-25 14:48:38.689,NaN,NaN,NaN,NaN,NaN,{'full_text': '@VSReddy_MP I think wantedly yo...,NaN
101912,2020-04-25 14:48:38+00:00,1254059751949942784,1254059751949942784,RT @DeepStateExpose: RETWEET! 5G is the real s...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,NaN,NaN,...,low,en,2020-04-25 14:48:38.825,{'created_at': 'Sat Apr 25 14:48:27 +0000 2020...,NaN,NaN,NaN,NaN,NaN,NaN
101913,2020-04-25 14:48:38+00:00,1254059752134455296,1254059752134455296,RT @bongofive: Diamond atangaza kuzilipia kodi...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,NaN,NaN,...,low,ro,2020-04-25 14:48:38.869,{'created_at': 'Sat Apr 25 13:22:51 +0000 2020...,NaN,NaN,NaN,NaN,NaN,NaN
101914,2020-04-25 14:48:38+00:00,1254059751945596930,1254059751945596928,RT @AjeetSonwarsha: “धार्मिक” एक्सपर्ट लोगों स...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,NaN,NaN,...,low,hi,2020-04-25 14:48:38.824,{'created_at': 'Sat Apr 25 10:08:53 +0000 2020...,NaN,NaN,NaN,NaN,NaN,NaN
101915,2020-04-25 14:48:38+00:00,1254059752201519104,1254059752201519104,RT @anderslindberg: För att förstå vad Anders ...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,NaN,NaN,...,low,sv,2020-04-25 14:48:38.885,{'created_at': 'Sat Apr 25 08:39:12 +0000 2020...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
twitterdf.dtypes

created_at                   datetime64[ns, UTC]
id                                         int64
id_str                                     int64
text                                      object
display_text_range                        object
source                                    object
truncated                                   bool
in_reply_to_status_id                    float64
in_reply_to_status_id_str                float64
in_reply_to_user_id                      float64
in_reply_to_user_id_str                  float64
in_reply_to_screen_name                   object
user                                      object
geo                                       object
coordinates                               object
place                                     object
contributors                             float64
is_quote_status                             bool
quote_count                                int64
reply_count                                int64
retweet_count                              int64
favorite_count                             int64
entities                                  object
extended_entities                         object
favorited                                   bool
retweeted                                   bool
possibly_sensitive                       float64
filter_level                              object
lang                                      object
timestamp_ms                      datetime64[ns]
retweeted_status                          object
quoted_status_id                         float64
quoted_status_id_str                     float64
quoted_status                             object
quoted_status_permalink                   object
extended_tweet                            object
withheld_in_countries                     object
dtype: object